server: extend tag completion
bakape/hydron pull request #76
Opened 2020-08-16 01:15 UTC by Kamuso

Closes #17, closes #25
Left out #54 because we pretty much have the "all categories" functionality by just not specifying a category, and undefined is used for regular tags.

2020-08-16 12:57 UTC, bakape requested changes

2020-08-16 12:57 UTC, bakape commented on db/tags.go
> +			typeQ = fmt.Sprintf(" and type = %d", common.Undefined)
Please move all cases of this into an embedded function to DRY this a bit. 
Something like 
```
completeWithPrefix := func (t common.TagType) {
  prefix += s[:i+1]
  s = s[i+1:]
  typeQ = fmt.Sprintf(" and type = %d", t)
}
```

2020-08-16 12:57 UTC, bakape commented on db/tags.go
> +		re := regexp.MustCompile(`^` + regexp.QuoteMeta(s[i+1:]) + `.*`)
Return error instead of panicking.

2020-08-16 12:57 UTC, bakape commented on db/tags.go
> +					re = regexp.MustCompile(`^` + regexp.QuoteMeta(s[i+2:]) + `.*`)
Return error instead of panicking.

2020-08-16 12:57 UTC, bakape commented on db/tags.go
> +		re := regexp.MustCompile(`^` + regexp.QuoteMeta(s) + `.*`)
Return error instead of panicking.

2020-08-16 20:19 UTC, Kamuso commented
Ok, updated. So what about #54, should it be closed?

2020-08-17 04:27 UTC, Kamuso commented
While I'm here, fixed a bug.

2020-08-22 10:15 UTC, bakape commented
Okay, thank you!

2020-08-22 10:16 UTC, bakape approved these changes

2020-08-22 10:16 UTC, merged